### ISSUE TITLE
Version 0.11

### ISSUE THREAD

**Issue by endel** [serjek/colyseus-hxjs#3]
Hey @serjek, 

Not sure if you're still using this project? Today I've released version 0.11 of the server and clients, which introduces a few breaking changes. You can see all the changes in the migration guide: https://docs.colyseus.io/migrating/0.11/

It would be great if you have some time to upgrade `colyseus-hxjs` as well!

Cheers!

**Comment by serjek** [comment]
Hey! I wasn't using project for a while because was busy with getting UI into acceptable shape in a project where I use it. Now that I'm almost done I will return to colyseus because eventually I would like to see my project released. So I will have a look at this in near future. Thank you for this update!

**Comment by serjek** [comment]
Done!
